%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 2

is_fisheye: 1
imu_topic: "/dji_sdk_1/dji_sdk/imu"
# imu_topic: "/dji_sdk_1/dji_sdk/imu"
image0_topic: "/stereo/left/image_raw"
image1_topic: "/stereo/right/image_raw"
output_path: "/home/xuhao/output"

depth_config: "depth.yaml"
cam0_calib: "up.yaml"
cam1_calib: "down.yaml"
image_width: 600 # For fisheye, this indicate the flattened image width; min 100; 300 - 500 is good for vins
image_height: 400
show_width: 1080

fisheye_fov: 235

enable_up_top: 1
enable_down_top: 1
enable_up_side: 1
enable_down_side: 1
enable_rear_side: 1
thres_outlier : 5.0
tri_max_err: 3.0
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0      # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 9.9970152931501111e-01, -2.4334070146456496e-02,
       -2.1691738831616180e-03, 2.4271285208706174e-02,
       2.4313045731037753e-02, 9.9966167038360143e-01,
       -9.2423250942725247e-03, 4.6146656309142874e-03,
       2.3933433745542093e-03, 9.1868273073508668e-03,
       9.9995493604037800e-01, 8.9835134676070530e-02, 0., 0., 0., 1. ]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 9.9985740148420199e-01, 1.3221990047149310e-02,
       1.0505031006729837e-02, 2.1768721164581610e-02,
       1.3173059971592354e-02, -9.9990212239267229e-01,
       4.7133985207440873e-03, 2.1485901422100902e-03,
       1.0566323307759515e-02, -4.5743429936555748e-03,
       -9.9993371190191072e-01, -2.4828776478011370e-02, 0., 0., 0., 1. ]




# body_T_cam0: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [1, 0, 0, 0.0392,
#          0, 1, 0, 0.0170,
#          0, 0, 1, 0.0662, 
#          0., 0., 0., 1 ]
# body_T_cam1: !!opencv-matrix
#    rows: 4
#    cols: 4
#    dt: d
#    data: [1, 0, 0, 0.0392,
#          0, -1, 0, 0.0170,
#          0, 0, -1, -0.0540, 
#          0., 0., 0., 1 ]

#Multiple thread support
multiple_thread: 1
#Gpu accleration support
use_gpu: 1
use_gpu_acc_flow: 1


depth_estimate_baseline: 0.05
top_cnt: 30
side_cnt: 30
max_solve_cnt: 30 # Max Point for solve; highly influence performace

min_dist: 20            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 0           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04 # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
# max_solver_time: 1.0  # max solver itration time (ms), to guarantee real time
# max_num_iterations: 100   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.85         # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
# td: -0.0736        #-0.0736 when use DJI IMU                       # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)#
td: 0.014686 #Use mynteye imu
#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/home/xuhao/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

#rectify
publish_rectify: 0              # whether publish rectified pose
cam0_rectify: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0, 0, 1,
         -1, 0, 0,
         0, -1, 0 ]

cam1_rectify: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0, 0, 1,
         -1, 0, 0,
         0, -1, 0 ]
